version: '3.9'

services:
  db:
    image: postgres:16
    container_name: creverse-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: creverse-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redisdata:/data
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: creverse-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: creverse@creverse.com
      PGADMIN_DEFAULT_PASSWORD: creverse
    ports:
      - '5050:80'
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
  redisdata: